import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";



const barlow_Condensed = Barlow_Condensed({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Epa! | Ensino por amor!",
  description: "Generated by create next app",
  icons: "/images/epa.ico",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={barlow_Condensed.className}>

        {children}

      </body>
    </html>
  );
}

