"use client";
import { Barlow_Condensed } from "next/font/google";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { Metadata } from "next";

import SplashScreen from "./components/SplashScreen";

const barlow_Condensed = Barlow_Condensed({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Epa! | Ensino por amor!",
//   description: "Generated by create next app",
//   icons: "/images/epa.ico",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const [isLoading, setIsLoading] = useState(isHome);

  useEffect(() => {
    if (isLoading) return;
  }, [isLoading]);

  return (
    <html lang="pt-br">
      <head>

      </head>
      <body className={barlow_Condensed.className}>
        {isLoading && isHome ? (
          <SplashScreen finishLoading={() => setIsLoading(false)} />

        ) : (
          <>
            {children}
          </>
        )}
      </body>
    </html>
  );
}
